### ISSUE TITLE
使用中的3DMigotoLoader拖入home/work后mods全部丢失被删除

### ISSUE THREAD

**Issue by 54yq** [numlinka/d3dxSkinManage#10]
如题，事先准备好的mod都没了，有无找回方法

**Comment by numlinka** [comment]
你不该那么做，在你了解其工作原理之前。
d3dxSkinManage 对 Mod 设置有冲突检查，在每次更新缓存数据表时都会检查 Mods 文件夹下的内容，并移除冲突和未在数据表中注册的内容，其目的是为了保证相同对象下的 Mod 是互斥的，以减少因为 hash 发生的冲突，如果你需要自己添加 Mod 到工作目录，应该在文件夹名前面加上一个下划线，以表示不要检查该文件夹。
但很抱歉，我没有办法帮助你恢复那些被删除的文件，我并没有设置回收站或类似的功能。
或许你可以使用一些文件恢复工具来尝试找回这些文件，它们只是在硬盘中被标记为删除，直到它们所在的块被真正清理或被覆写之前，这些文件是可以将恢复的。
