### ISSUE TITLE
管理器数据错误

### ISSUE THREAD

**Issue by memgkong** [numlinka/d3dxSkinManage#13]
[我的d3d管理器突然出现了数据异常，几乎所有的mod都被卸载，本来我已经完全整理好了我的所有mod，并基本都添加了预览图，但是很多的分类突然消失了，然后很多mod也都不再显示，比如图中我的绫华本来有20多个mod，现在只显示这些![屏幕截图 2024-04-22 013037](https://github.com/numlinka/d3dxSkinManage/assets/152505215/a2f95bba-9aa0-441b-bf61-f5c7c3989821)
，我查看了文件，这些mod都还在，预览图文件也还在，
![image](https://github.com/numlinka/d3dxSkinManage/assets/152505215/9de38e1c-267c-4620-8900-d1bf33d88cfc)
![image](https://github.com/numlinka/d3dxSkinManage/assets/152505215/afd99fed-fd18-45c9-aaae-73022289eda7)
但是它们现在完全不显示，我不知道怎么回事，也不知道该怎么解决，整理好这些mod耗费我相当大的精力，我实在不想重新整理。

**Comment by numlinka** [comment]
一直以来，我只装载很少量的插件，然而最近在尝试更多的一些插件时我遇到了类似的问题，Mod 全被卸载，但似乎没有丢失数据，我不清楚这个问题出现的原因，或许这是个巧合？如果索引文件损坏，程序应该能在出现错误时进行提醒，当然这不排除某些功能出现冲突，或者使用了不安全的函数，亦或者是计算机去抽了根烟。

虽然不知道具体原因，但是我们可以猜，程序主要通过用户目录 modsIndex 文件夹下的 json 文件来关联各个资源文件，它很重要，所以当 index 文件损坏或丢失时程序会无法正确认知到与其向关联的资源文件。而当数据莫名其妙缺失时，就可能是某种不可知的问题导致了这里面的文件损坏或丢失。

但有些时候是人为的，有少部分人在尝试合并数据时将里面的文件覆盖了，这也会导致数据丢失。

我试图打造一个属于自己的程序框架，而这个项目作为一个试验品存在着诸多设计问题，如果你对数据安全比较敏感，请定期备份 modsIndex 目录。
