### ISSUE TITLE
請問最新版的XXMI如何在管理器使用 

### ISSUE THREAD

**Issue by lavender7410** [numlinka/d3dxSkinManage#30]
純小白 真的要把一個東西搞明白真心頭痛 好不容易能明白如何添加MOD進管理器 這階段又有3dmigoto WWMI ZZMI  GIMI和SRMI軟體包 什麼的 
一堆加載器 結果現在更新一個 XXMI 全新的加載器似乎是一個新平台
https://github.com/SpectrumQT/XXMI-Launcher

**Comment by lavender7410** [comment]
https://gamebanana.com/tools/17252

**Comment by numlinka** [comment]
經過簡單的測試，這似乎是一個管理器 (Manager) 而不是載入器 (Loader) ，它任然使用 WWMI ZZMI GIMI SRMI 等工具載入模組，你不應該在一個遊戲上同時使用兩種不同的模組管理工具，因此它也不應該併入 d3dxSkinManage 而是作為一個獨立的工具使用。

**Comment by lavender7410** [comment]
了解了 感謝
