### ISSUE TITLE
星铁启动问题

### ISSUE THREAD

**Issue by ZDLSHLS** [numlinka/d3dxSkinManage#4]
使用d3d 1.5.30版本尝试三种版本启动加载器（图1） 均以失败告终，再依次从工作目录使用管理员启动也无法在启动游戏后左下角出现信息或“嘟”声并出现绿字 遂自行下载单独的MOD加载器（图2） 只有使用管理员才能启动加载器成功（图3）  

问题来了：
我觉得启动麻烦 自己写了个简单的批处理文件（图4）
但是由于个人编程能力和学习能力匮乏 在网上搜一圈也没解决使用管理员启动这个的问题。。尝试过bat转exe 再使用管理员打开——无果。寻求帮助 <3

另外我发现即使通过管理员启动快捷键方式的加载器也无效。我晕 昨天上午帮别人弄了星铁MOD 跟我一个版本 还写了相同的bat启动都成功了。。 结果自己却出了问题
![`$ Q Y6ENS)~FIX6QL~)XE2](https://github.com/numlinka/d3dxSkinManage/assets/41809962/f162b12c-6354-4458-b45a-2ad00d4e03b6)
![2NQ7RBU9 X I)}W462_8LXH](https://github.com/numlinka/d3dxSkinManage/assets/41809962/9c8459fd-bda7-439e-a287-641ad5f8f304)

**Comment by ZDLSHLS** [comment]
![@3 CC9`}DB$ }C0QK6MG64N](https://github.com/numlinka/d3dxSkinManage/assets/41809962/4c62a2c8-c99c-4f21-b8ab-52751758faf0)
![2L50ZQEPEIS3%X@CB$RLJQV](https://github.com/numlinka/d3dxSkinManage/assets/41809962/6c60e142-056d-4e8c-8f5f-fcb22195b262)

**Comment by ZDLSHLS** [comment]
新人第一次写issue 表达不好请见谅 :3

**Comment by numlinka** [comment]
你可以在 "环境设置" 页面打开 3DMigoto 的工作目录，并将你的 3DMigoto 版本覆盖进去。程序在唤起 3DMigotoLoader 时默认的 ShellExecute 模式是 "runas" ，及以管理员权限运行 (d3dxSkinManage 程序本身不需要管理员权限，我不推荐你那么做) 。

在一些特殊情况下，你可能需要修改工作目录的 "scheme.json" 文件，它决定了程序会如何处理和启动 3DMigotoLoader ，其中，你需要留意的是 "launch" 和 "set-need" 的值，"launch" 决定程序会唤起哪个可执行文件（它可以是一个批处理脚本），"set-need" 决定程序是否会修改 “d3dx.ini” 文件，使其目标路径与程序内的游戏路径一致。如果你尝试加载过内置的 "_v7.0_SRMI_development" 版本，那么你大概率不需要修改这个文件。

3DMigoto 需要有管理员权限才能将 dll 注入到游戏进程中，程序在唤醒加载器时会自动为其请求管理员权限，因此你并不需要担心这个问题。如果 3DMigoto 未能正确注入到游戏中，例如 Error initialization hook (钩子初始化失败) 等问题时，可以尝试关闭杀毒软件后重试。

如果你希望批处理脚本 (Batch) 可以自动请求管理员权限，可以在脚本开头插入如下命令
`%1 start "" mshta vbscript:createobject("shell.application").shellexecute("""%~0""","::",,"runas",1)(window.close)&exit`

**Comment by ZDLSHLS** [comment]
感谢如此专业的回答！
