### ISSUE TITLE
mod炸了

### ISSUE THREAD

**Issue by djsalkjd** [numlinka/d3dxSkinManage#6]
文件加载进去之前可以用的突然全炸了武器的mod还能用就是人物的不能用了

**Comment by numlinka** [comment]
你的描述过于简陋，以至于我无法定位问题的具体原因。
但类似的问题可以参考[常见问题](https://d3dxskinmanage.numlinka.com/#/help/faqs)。

**Comment by djsalkjd** [comment]
> 你的描述过于简陋，以至于我无法定位问题的具体原因。 但类似的问题可以参考[常见问题](https://d3dxskinmanage.numlinka.com/#/help/faqs)。

可是我的mod文件都是好的，我加载进入游戏全是崩的用了插件也没用我把mod重下把3dx也重新下了甚至把原神也重新下载了但是就是没用
![QQ截图20240318215725](https://github.com/numlinka/d3dxSkinManage/assets/163725626/045546a7-f844-461e-82bf-d5323077129e)

**Comment by Askwind** [comment]
https://gamebanana.com/tools/16084 可以尝试到香蕉网下补丁修复

**Comment by FFDFK** [comment]
![image](https://github.com/numlinka/d3dxSkinManage/assets/101695618/41c94ac0-a539-4c4e-8a25-590bd7f41b81)huo或许你的这个选项没有关闭

**Comment by FFDFK** [comment]
角色动态高精度
