### ISSUE TITLE
mod 压缩文件夹包含韩文字符串无法安装

### ISSUE THREAD

**Issue by yanghuan** [numlinka/d3dxSkinManage#7]
mod 压缩文件夹包含韩文字符串无法安装

**Comment by numlinka** [comment]
通常情况下，我们期望 dropfiles 收到的内容编码与系统编码相同（在国内通常为 GBK），或者为 UTF-8 编码，而在韩国的计算机系统编码通常为 EUC-KR ，这会导致其中的非 ASCII 无法被正确识别，正确的做法是，不要和编码较劲，使用纯英文字符是最简单的解决方式。
