### ISSUE TITLE
mod不起作用

### ISSUE THREAD

**Issue by FFDFK** [numlinka/d3dxSkinManage#8]
在官网下载了原神4.5版本后，使用管理器开启游戏，然而角色的外表并没有改变。

**Comment by numlinka** [comment]
https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

**Comment by FFDFK** [comment]
哦不....只是我不知道是哪里出了问题，没有头绪

**Comment by FFDFK** [comment]
文件似乎都是好的，管理器是新的，mod是gamebanana下载完直接导入的

**Comment by numlinka** [comment]
请检查你的 3dmigoto 是否正常工作，如果没有可以尝试切换版本或尝试手动运行；如果注入器工作异常，请检查你的安全软件是否阻止了该行为或更新你的系统版本；如果注入器在游戏启动前就有了注入行为，请检查设置是否正确或是否有僵尸进程滞留在系统中；如果存在僵尸进程可以尝试使用 taskkill 终止它或重启你的计算机。
或许你可以在控制面板的电源管理中关闭快速启动以减少部分重启无法解决的问题。

**Comment by FFDFK** [comment]
差点忘了回来说，切换3dmigoto版本后解决了
