### ISSUE TITLE
分类很多，对象显示不全

### ISSUE THREAD

**Issue by lmtz666** [numlinka/d3dxSkinManage#9]
为什么分类有很多，但是对象就三个呀
![屏幕截图 2024-04-01 201638](https://github.com/numlinka/d3dxSkinManage/assets/127282348/ed1079bb-251b-412c-a004-a74fd981d684)

**Comment by numlinka** [comment]
你没有与对象相关联的 MOD ，所以列表在构建时会排除这些无用的选项，
这并不是程序漏洞，因为它就是这么设计的。

**Comment by numlinka** [comment]
或许在提问前你可以先阅读文档，可以避免这些无效的问题。

**Comment by lmtz666** [comment]
@numlinka 感谢回答，但是我看了几遍文档没有找到相关问题的答案，或者我不知道我的问题对应文档的那一部分，可以麻烦进一步指点一下吗，谢谢
